bug/ISSUE149-border-not-rendered
DHBW-FN/OxideWM pull request #230
Opened 2023-03-03 19:18 UTC by janschaible

2023-03-03 19:20 UTC, janschaible commented
@FelixSchladt @B1TC0R3 should only the focused window have a border ?:)
If so, should the border be inwards or outwards ?:)

2023-03-03 21:23 UTC, FelixSchladt commented
I think every window should have a border.
We have two different colors defined in our config.
The focused window will have a different color than the not focused one.

To have a hex color as bg color for the frame we will need to draw this with cairo like in the status bar.

2023-03-03 21:32 UTC, FelixSchladt commented
This could be part of a follow up ticket

2023-03-06 09:58 UTC, gungula requested changes
teamwork with @FelixSchladt

2023-03-06 09:58 UTC, gungula commented on src/screeninfo/mod.rs
> +        self.status_bar.as_mut().unwrap().draw_without_border();
makes sense but i dont really get why the statusbar didnt have any borders around it

2023-03-06 09:58 UTC, gungula commented on src/windowstate.rs
> +    pub fn draw_without_border(&self){
why do we have three functions?

I would think we only need two. One normal ones with gaps and frames, for fullscreen and status bar.
Another one with gaps and frames for normal windows.

2023-03-06 09:58 UTC, gungula commented on src/windowstate.rs
> +            .x(0)
why is this hardcoded?

2023-03-06 09:58 UTC, gungula commented on src/windowstate.rs
> +            .x(self.border_width as i32)
what happened to the gaps?

2023-03-06 09:58 UTC, gungula commented on src/workspace/mod.rs
> +        window.draw_without_border();
all windows should have a border, focused or not.

The color of the border should differentiate.

I would postpone this though for now and implement this later.
The focusing could be given with a parameter. WDY think?

For now we could do black and white pixel for unfocused/focused?

2023-03-30 13:38 UTC, FelixSchladt commented
there is a poc using the border width attribute. 
5f669620c77b2a24c638c7fd196ced990d2fae65

This should fix the focus issues of the current solution and easy handling by not requiring a seperate frame window to be created...

2023-06-22 14:10 UTC, FelixSchladt commented
closing this pr as code is more a workaround and does not provide the desired functionality

2023-06-22 14:10 UTC, closed without merging