Bug/issue235 oxide msg panic
DHBW-FN/OxideWM pull request #236
Opened 2023-03-14 11:19 UTC by B1TC0R3

Fixed bug from issue 235.

2023-03-14 12:35 UTC, janschaible commented
what do you want to merge first ?:) your tests rewritten in python ?:)

2023-03-16 18:56 UTC, FelixSchladt requested changes

2023-03-16 18:56 UTC, FelixSchladt commented on extensions/oxide-ipc/src/lib.rs
> +    sent_event("gotoworkspace", Some(index.to_string())).ok();
I think it would be best to return results here as this makes most sense in the context of a library

2023-03-16 18:56 UTC, FelixSchladt commented on extensions/oxide-ipc/src/lib.rs
> +    sent_event("gotoworkspace", Some("next".to_string())).ok();
I think it would be best to return results here as this makes most sense in the context of a library

2023-03-16 18:56 UTC, FelixSchladt commented on extensions/oxide-ipc/src/lib.rs
> +    sent_event("gotoworkspace", Some("prev".to_string())).ok();
I think it would be best to return results here as this makes most sense in the context of a library

2023-03-30 13:10 UTC, FelixSchladt commented on extensions/oxide-ipc/src/lib.rs
> +    sent_event("gotoworkspace", Some("prev".to_string())).ok();
follow up ticket

2023-03-30 13:10 UTC, FelixSchladt commented on extensions/oxide-ipc/src/lib.rs
> +    sent_event("gotoworkspace", Some("next".to_string())).ok();
follow up ticket

2023-03-30 13:11 UTC, FelixSchladt approved these changes

2023-03-30 13:13 UTC, merged